/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "n4.4.2-95-ga8f16d4eb4-20220930"
#endif /* AVUTIL_FFVERSION_H */
